const mongoose = require('mongoose')
const Schema = mongoose.Schema;
// const bcrypt = require('bcrypt')
const FeeReceiptSchema = new Schema({
    receipt_date:{
        type:String,        
    },
    receipt_no:{
        type:String,        
    },
    ref_receipt_no:{
        type:String,
    },
    session:{
        type:String,        
        required:true,
    }, 
    admission_no:{
        type:String,        
    },
    account_no:{
        type:String,        
    },
    prospectus_fee:{
        type:String,        
    },
    registration_fee:{
        type:String,        
    },
    admission_fee:{
        type:String,        
    },
    security_fee:{
        type:String,        
    },
    report_card_and_diary:{
        type:String,        
    },
    annual_prize_day:{
        type:String,        
    }, 
    development_fund:{
        type:String,        
    },
    school_magazin:{
        type:String,        
    },
    annual_sports_day:{
        type:String,        
    },
    examination_fee:{
        type:String,        
    }, 
    med_board_reg:{
        type:String,        
    },
    library_fee:{
        type:String,        
    },
    tution_fee:{
        type:String,        
    },
    computer_fee:{
        type:String,        
    },
    science_fee:{
        type:String,        
    },
    bus_fare:{
        type:String,        
    },
    total_monthly_fee:{
        type:String,        
    },
    grand_total:{
        type:String,        
    },
    payment_mode:{
        type:String,        
    },
    bank:{
        type:String,        
    },
    bank_v_no:{
        type:String,        
    },
    check_no:{
        type:String,        
    },
    bank_date:{
        type:String,        
    },
},{timestamps: true}
)

mongoose.model('Receipt',FeeReceiptSchema);
